In [1]:
import numpy as np
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nAddition:\n", A + B)
print("\nSubtraction:\n", A - B)
print("\nElement-wise Multiplication:\n", A * B)
print("\nMatrix Multiplication:\n", A @ B)
print("\nTranspose of A:\n", A.T)
print("\nSquare of A:\n", A ** 2)
print("\nRow Sum:\n", np.sum(A, axis=1))
print("\nColumn Sum:\n", np.sum(A, axis=0))
print("\nFlattened Matrix:")
print(A.flatten())
print("\nReshaped Matrix (1 x 4):")
print(A.reshape(1, 4))
print("\nRotated Matrix (90°):")
print(np.rot90(A))
print("\nFlipped Matrix:")
print(np.flipud(A))
M = np.array([[1, 2],
              [3, 4]])
print("\nMatrix for SVD:\n", M)
U, S, VT = np.linalg.svd(M)
print("\nU Matrix:\n", U)
print("\nSingular Values:\n", S)
print("\nVᵀ Matrix:\n", VT)
Sigma = np.diag(S)
Reconstructed = U @ Sigma @ VT
print("\nReconstructed Matrix:\n", Reconstructed)

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Addition:
 [[ 6  8]
 [10 12]]

Subtraction:
 [[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]

Matrix Multiplication:
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Square of A:
 [[ 1  4]
 [ 9 16]]

Row Sum:
 [3 7]

Column Sum:
 [4 6]

Flattened Matrix:
[1 2 3 4]

Reshaped Matrix (1 x 4):
[[1 2 3 4]]

Rotated Matrix (90°):
[[2 4]
 [1 3]]

Flipped Matrix:
[[3 4]
 [1 2]]

Matrix for SVD:
 [[1 2]
 [3 4]]

U Matrix:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]

Singular Values:
 [5.4649857  0.36596619]

Vᵀ Matrix:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]

Reconstructed Matrix:
 [[1. 2.]
 [3. 4.]]
