In [1]:
import numpy as np
r = int(input("Enter number of rows: "))
c = int(input("Enter number of columns: "))

print("Enter elements of Matrix A:")
A = np.array([[int(input()) for j in range(c)] for i in range(r)])
print("Enter elements of Matrix B:")
B = np.array([[int(input()) for j in range(c)] for i in range(r)])

print("\nMatrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition:")
print(A + B)
print("\nSubtraction:")
print(A - B)
print("\nElement-wise Multiplication:")
print(A * B)
print("\nMatrix Multiplication:")
print(np.dot(A, B))
print("\nTranspose of Matrix A:")
print(A.T)
print("\nTranspose of Matrix B:")
print(B.T)

Enter number of rows:  2
Enter number of columns:  2


Enter elements of Matrix A:


 5
 3
 8
 7


Enter elements of Matrix B:


 1
 4
 7
 8



Matrix A:
[[5 3]
 [8 7]]

Matrix B:
[[1 4]
 [7 8]]

Addition:
[[ 6  7]
 [15 15]]

Subtraction:
[[ 4 -1]
 [ 1 -1]]

Element-wise Multiplication:
[[ 5 12]
 [56 56]]

Matrix Multiplication:
[[26 44]
 [57 88]]

Transpose of Matrix A:
[[5 8]
 [3 7]]

Transpose of Matrix B:
[[1 7]
 [4 8]]
